
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoint:
    health:
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: metrics,health,refresh,info

keystore:
  type: PKCS12
  path: ./keystores/keystore.pkcs12
  password: bigtree
  alias: bigtree

encryption:
  key:
    id: bigtree-encryption-key-id